version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          command: |
            sudo apt-get install -y libsm6 libxext6 libxrender-dev

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r tests/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install package
          command: |
            . venv/bin/activate
            python setup.py install
            python setup.py clean
            python setup.py sdist bdist_wheel
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run --source tf_semantic_segmentation -m py.test tests --doctest-modules --pep8
            coverage report -m
            codecov
